### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by yxy-kunling** [HBX-hbx/Mistral-Interact#5]
TypeError: Block.forward() got an unexpected keyword argument 'past_key_value'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/yxy/Mistral-Interact-master/./src/test_one_new.py", line 280, in <module>
    main()
  File "/data/yxy/Mistral-Interact-master/./src/test_one_new.py", line 277, in main
    main_loop(args, raw_tasks, tokenizer, model)
  File "/data/yxy/Mistral-Interact-master/./src/test_one_new.py", line 206, in main_loop
    print(pred)
          ^^^^
UnboundLocalError: cannot access local variable 'pred' where it is not associated with a value

**Comment by HBX-hbx** [comment]
Refer to https://github.com/OpenBMB/Tell_Me_More/issues/3
